__variables__:
  dir: foobar
  rname: Report name
  meta:
  gs_nonzero:
  gsa: True
  plage: True
  fgsea: True
  gsa_comparison:
  enrichment_summary:
  sig_threshold: 0.01
  contrasts:
    foobar: contrast_name
  fgsea_only:
  plage_only:

name: ?rname
datasets:
  metadata:
    path: ?meta
    separator: "\t"
  gs_nonzero:
    path: ?gs_nonzero
    separator: "\t"
  ?if enrichment_summary is not None:
    en_summary:
      path: ?enrichment_summary
      separator: "\t"
  ?if gsa:
    gsa:
      path: ?f"{dir}/gsa.tsv"
      separator: "\t"
      links:
        set details:
          column: set_name
          table-row: Metadata/set_name
          optional: true
        set nonzero frequency:
          column: set_name
          table-row: Nonzero/name
          optional: true
  ?if fgsea:
    ?for item in contrasts:
      ?if fgsea_only is None or item in fgsea_only:
        ?f"fgsea_{item}":
          path: ?f"{dir}/fgsea_{item}.tsv"
          separator: "\t"
          links:
            set details:
              column: pathway
              table-row: Metadata/set_name
              optional: true
            set nonzero frequency:
              column: pathway
              table-row: Nonzero/name
              optional: true
  ?if plage:
    plage_decideTests:
      path: ?f"{dir}/plage_decideTests.tsv"
      separator: "\t"
      links:
        set details:
          column: set_name
          table-row: Metadata/set_name
          optional: true
        set nonzero frequency:
          column: set_name
          table-row: Nonzero/name
          optional: true
    ?for item in contrasts:
      ?if plage_only is None or item in plage_only:
        ?f"plage_toptreat_{item}":
          path: ?f"{dir}/plage_topTreat_{item}.tsv"
          separator: "\t"
          links:
            set details:
              column: set_name
              table-row: Metadata/set_name
              optional: true
            set nonzero frequency:
              column: set_name
              table-row: Nonzero/name
              optional: true

views:
  Metadata:
    dataset: metadata
    desc: "Descriptions and statistics for gene sets"
    render-table:
      columns:
        set_name:
          display-mode: hidden
  Nonzero:
    dataset: gs_nonzero
    desc: "Fraction of nonzero genes in the the gene set, averaged across samples with the given group. The columns are 'group_type-member_of_type'"
  ?if gsa:
    GSA:
      dataset: gsa
      desc: "Results from Gene Set Analysis"
      render-table:
        columns:
          ?f"p-value:up-regulated in {gsa_comparison[0]}":
            spell:
              url: v1.3.0/stats/p-value
              with:
                significance_threshold: ?sig_threshold
          ?f"p-value:up-regulated in {gsa_comparison[1]}":
            spell:
              url: v1.3.0/stats/p-value
              with:
                significance_threshold: ?sig_threshold
  ?if enrichment_summary is not None:
    Category counts:
      dataset: en_summary
      desc: "Counts of statistically significant gene sets in each category for each test"
  ?if plage:
    PLAGE decideTests:
      dataset: plage_decideTests
      desc: "Hypothesis test conclusions from PLAGE\n-1 indicates significantly negative, 0 not significant and 1 significantly positive"
      render-table:
        columns:
          ?for item in contrasts:
            ?item:
              plot:
                ticks:
                  domain:
                    - -1
                    - 1
    ?for key, value in contrasts.items():
      ?if plage_only is None or key in plage_only:
        ?f"PLAGE topTreat {key}":
          dataset: ?f"plage_toptreat_{key}"
          desc: ?f"topTreat results for contrast '{value}'"
          render-table:
            columns:
              P.Value:
                spell:
                  url: v1.3.0/stats/p-value
                  with:
                    significance_threshold: ?sig_threshold
              adj.P.Val:
                spell:
                  url: v1.3.0/stats/p-value
                  with:
                    significance_threshold: ?sig_threshold
  ?if fgsea:
    ?for key, value in contrasts.items():
      ?if fgsea_only is None or key in fgsea_only:
        ?f"FGSEA {key}":
          dataset: ?f"fgsea_{key}"
          desc: ?f"FGSEA results for DE genes identified with contrast '{value}'"
          render-table:
            columns:
              pval:
                spell:
                  url: v1.3.0/stats/p-value
                  with:
                    significance_threshold: ?sig_threshold
              padj:
                spell:
                  url: v1.3.0/stats/p-value
                  with:
                    significance_threshold: ?sig_threshold
              leadingEdge:
                display-mode: hidden
