configfile: "env.yaml"


from datetime import date

# Use these variables to specify output
REPOS = config["out"]["repos"] if not config["test"] else config["out"]["test_repos"]
OUT = config["out"]["root"] if not config["test"] else f"{config['out']['root']}/tests"
TODAY = date.today().isoformat()
DATE = config.get("date")


onstart:
    if not DATE:
        raise ValueError(
            f"""
            Key-value pair `date` must be provided in the config! On cli: --config date=DATE
            The current date is {TODAY}
            """
        )
    try:
        date.fromisoformat(DATE)
    except ValueError:
        raise ValueError(
            f"""
            `date` must be in the format YYYY-MM-DD
            The current date is {TODAY}
            """
        )


if RUN := config.get("run"):
    pass
else:
    RUN = ""
    print("WARNING: No run name provided, pass one with --config run=<name>")

if ov := config.get("override"):
    with open(ov, "r") as y:
        config.update(yaml.safe_load(y))
    print(f"Overriding config with file {ov}")
else:
    print(
        "WARNING: no overriding config provided, pass one with --config override=<file>"
    )
    print("Using default configuration..")


if config["test"] and not config.get("no_cpu"):
    config["dl"]["device"] = "cpu"
